# yaml 配置实例
version: '3'
services:
  php:
    image: php:ext-redis-mongo
    container_name: php7.4-ext-redis-mongo
    volumes:
      - ./data:/www
  nginx:
    image: nginx:latest
    container_name: php-nginx
    ports:
    - 8080:80
    volumes:
    - ./data:/usr/share/nginx/html
    - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

