# yaml 配置实例
version: '3'
services:
  #redis 服务
  redis:
    #redis镜像
    image: redis:latest
    container_name: redis-service
    #端口映射
    ports:
      - 6379:6379
    #目录映射
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - .redis/data:/data
      - /etc/localtime:/etc/localtime   #这个是使用宿主机时区，比下面的有效 （下面两种设置方法 有些镜像的系统无效 比如：alpine）
    #容器内执行的命令
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    environment:
      #设置时区
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai

  #mysql 服务
  mysql:
    image: mysql:latest
    container_name: mysql-service
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    #环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-pwd
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai

  #php-fpm 服务
  php-fpm:
    image: php:ext-redis-mongo
    container_name: php7.4-ext-redis-mongo
    volumes:
        - ./php7.4-nginx/data:/www
        - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai

  #nginx 服务
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./php7.4-nginx/data:/usr/share/nginx/html
      - ./php7.4-nginx/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime
    links:
      - php-fpm
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    #environment:
    #  - SET_CONTAINER_TIMEZONE=true
    #  - CONTAINER_TIMEZONE=Asia/Shanghai
